/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import com.google.common.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class App {
    public static void main(String[] args){
        String path = "./app/src/main/resources/recentquotes.json";
        gettingInfo(path);
    }
    public static List gettingInfo(String extension) {

        Gson gson = new Gson();
        FileReader fileReader = null;

        try {
            fileReader = new FileReader(extension);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
            System.out.println("Error");
        }



        Type quotesList = new TypeToken<ArrayList<Quotes>>() {}.getType();

        List<Quotes> fileQuotes = gson.fromJson(fileReader, quotesList);


        int randomValue = (int)(Math.random() * fileQuotes.size());

        System.out.println("Quote Index is : " + randomValue);
        System.out.println(fileQuotes.get(randomValue).toString());

        return fileQuotes;

    }
}
